export const PROFILE_UPDATE_REQUEST = "PROFILE_UPDATE_REQUEST";
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_FAILS = "PROFILE_UPDATE_FAILS";
export const CLEAR_ERRORS ="CLEAR_ERRORS"
export const PASSWORD_CHANGE_REQUEST="PASSWORD_CHANGE_REQUEST";
export const PASSWORD_CHANGE_SUCCESS="PASSWORD_CHANGE_SUCCESS";
export const PASSWORD_CHANGE_FAILS="PASSWORD_CHANGE_FAILS";