export const REGISTER_USER_REQUEST='REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS='REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILS='REGISTER_USER_FAILS'
export const CLEAR_ERRORS='CLEAR_ERRORS'